### ISSUE TITLE
Setup CI/Test building on Linux

### ISSUE THREAD

**Issue by VariantXYZ** [PolarisTeam/PolarisCore#2]
Setup Linux CI and add it to PRs to develop and develop merging into master.

**Comment by VariantXYZ** [comment]
Closed by #17

**Comment by VariantXYZ** [comment]
Re-opening because appveyor isn't in yet

**Comment by VariantXYZ** [comment]
@alama is this closed now

**Comment by alama** [comment]
Yea, there no 'unit' testing but yea, this can be closed
