### ISSUE TITLE
Setup initial login support

### ISSUE THREAD

**Issue by VariantXYZ** [PolarisTeam/PolarisCore#5]
PolarisAuth high level requirements:
- Be an open facing server on a specific IP/Port for incoming clients
- Handle the user state from the login screen up-to but not including character selection
- Pass a client through to PolarisServer if authentication passes, handle replying with the correct information if authentication failed
- Handle checking for maintenance modes/user 'account' level, as well as other possible UserAuthenticated events (such as checking for whether the user is banned)

Any other high level requirements that you guys think should belong with the auth server?

**Comment by TheCrimsonDevil** [comment]
testing the discord bot

**Comment by VariantXYZ** [comment]
Will require account database setup as well

**Comment by Kyle873** [comment]
See #6 re account database.
